title: "EDM Portfolio"
description: "Enterprise Data Management Portfolio"
author: Sanidad, Justine Reinn V.
logo: "/pfp/pfp.jpg"

show_downloads: true

github:
  is_project_page: true
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

